src/Entity/Orders.php
<?php

namespace App\Entity;

use App\Repository\OrdersRepository;
use DateTimeImmutable;
use DateTimeZone;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrdersRepository::class)]
class Orders
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name_order = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'orders', targetEntity: RawMaterialsOrdered::class, orphanRemoval: true)]
    private Collection $raw_material_ordered;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Worksites $worksite = null;

    #[ORM\ManyToOne(inversedBy: 'orders')]
    private ?Supplier $supplier = null;

    #[ORM\Column(length: 255)]
    private ?string $reference = null;

    #[ORM\Column(nullable: true)]
    private ?int $total_price = null;

    #[ORM\Column(nullable: true)]
    private ?int $number_raw_material_ordered = null;

    public function __construct()
    {
        $this->raw_material_ordered = new ArrayCollection();

        $date = new DateTimeImmutable();
        $timezone = new DateTimeZone('Europe/Paris');
        $created_at =  $date->setTimezone($timezone);
        $this->created_at = $created_at;
    }

    public function __toString()
    {
        return $this->name_order;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameOrder(): ?string
    {
        return $this->name_order;
    }

    public function setNameOrder(string $name_order): self
    {
        $this->name_order = $name_order;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $timezone = new DateTimeZone('Europe/Paris');
        $newDate = $updated_at->setTimezone($timezone);

        $this->updated_at = $newDate;

        return $this;
    }

    /**
     * @return Collection<int, RawMaterialsOrdered>
     */
    public function getRawMaterialOrdered(): Collection
    {
        return $this->raw_material_ordered;
    }

    public function addRawMaterialOrdered(RawMaterialsOrdered $rawMaterialOrdered): self
    {
        if (!$this->raw_material_ordered->contains($rawMaterialOrdered)) {
            $this->raw_material_ordered->add($rawMaterialOrdered);
            $rawMaterialOrdered->setOrders($this);
        }

        return $this;
    }

    public function removeRawMaterialOrdered(RawMaterialsOrdered $rawMaterialOrdered): self
    {
        if ($this->raw_material_ordered->removeElement($rawMaterialOrdered)) {
            // set the owning side to null (unless already changed)
            if ($rawMaterialOrdered->getOrders() === $this) {
                $rawMaterialOrdered->setOrders(null);
            }
        }

        return $this;
    }

    public function getWorksite(): ?Worksites
    {
        return $this->worksite;
    }

    public function setWorksite(?Worksites $worksite): self
    {
        $this->worksite = $worksite;

        return $this;
    }

    public function getSupplier(): ?Supplier
    {
        return $this->supplier;
    }

    public function setSupplier(?Supplier $supplier): self
    {
        $this->supplier = $supplier;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getTotalPrice(): ?int
    {
        return $this->total_price;
    }

    public function setTotalPrice(?int $total_price): self
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getNumberRawMaterialOrdered(): ?int
    {
        return $this->number_raw_material_ordered;
    }

    public function setNumberRawMaterialOrdered(?int $number_raw_material_ordered): self
    {
        $this->number_raw_material_ordered = $number_raw_material_ordered;

        return $this;
    }
}

src/Entity/RawMaterials.php
<?php

namespace App\Entity;

use App\Repository\RawMaterialsRepository;
use DateTimeImmutable;
use DateTimeZone;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RawMaterialsRepository::class)]
class RawMaterials
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name_raw_material = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(mappedBy: 'raw_material', targetEntity: RawMaterialsOrdered::class)]
    private Collection $raw_material_ordered;

    #[ORM\ManyToOne(inversedBy: 'rawMaterials')]
    #[ORM\JoinColumn(nullable: false)]
    private ?RawMaterialsCategories $category = null;

    #[ORM\Column(length: 255)]
    private ?string $unit = null;

    #[ORM\Column(nullable: true)]
    private ?int $price = null;

    public function __construct()
    {
        $this->raw_material_ordered = new ArrayCollection();
        $date = new DateTimeImmutable();
        $timezone = new DateTimeZone('Europe/Paris');
        $created_at =  $date->setTimezone($timezone);
        $this->created_at = $created_at;
    }

    public function __toString()
    {
        return $this->name_raw_material;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameRawMaterial(): ?string
    {
        return $this->name_raw_material;
    }

    public function setNameRawMaterial(string $name_raw_material): self
    {
        $this->name_raw_material = $name_raw_material;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, RawMaterialsOrdered>
     */
    public function getRawMaterialOrdered(): Collection
    {
        return $this->raw_material_ordered;
    }

    public function addRawMaterialOrdered(RawMaterialsOrdered $rawMaterialOrdered): self
    {
        if (!$this->raw_material_ordered->contains($rawMaterialOrdered)) {
            $this->raw_material_ordered->add($rawMaterialOrdered);
            $rawMaterialOrdered->setRawMaterial($this);
        }

        return $this;
    }

    public function removeRawMaterialOrdered(RawMaterialsOrdered $rawMaterialOrdered): self
    {
        if ($this->raw_material_ordered->removeElement($rawMaterialOrdered)) {
            // set the owning side to null (unless already changed)
            if ($rawMaterialOrdered->getRawMaterial() === $this) {
                $rawMaterialOrdered->setRawMaterial(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?RawMaterialsCategories
    {
        return $this->category;
    }

    public function setCategory(?RawMaterialsCategories $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUnit(): ?string
    {
        return $this->unit;
    }

    public function setUnit(string $unit): self
    {
        $this->unit = $unit;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
}

src/Controller/Admin/RawMaterialsController.php
<?php

namespace App\Controller\Admin;

use App\Entity\RawMaterials;
use App\Form\RawMaterialsType;
use App\Form\SearchFormType;
use App\Repository\OrdersRepository;
use App\Repository\RawMaterialsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/materiaux')]
class RawMaterialsController extends AbstractController
{
    #[Route('/', name: 'app_raw_materials_index', methods: ['GET', 'POST'])]
    public function index(RawMaterialsRepository $rawMaterialsRepository, Request $request, OrdersRepository $ordersRepository): Response
    {
        $rawMaterial = new RawMaterials();
        $searchForm = $this->createForm(SearchFormType::class, $rawMaterial, ['method' => 'POST']);
        $searchForm->handleRequest($request);

        $list = $rawMaterialsRepository->findAll();

        if ($searchForm->isSubmitted() && $searchForm->isValid()) {
            $search = $searchForm->getViewData()->getNameRawMaterial();
            $category = $searchForm->getViewData()->getCategory();
            $list = $rawMaterialsRepository->findByNameAndCategory($search, $category);
        }
        
        $lastOrders = $ordersRepository->findBy([], ['id' => 'DESC'], 10, 0);

        return $this->renderForm('raw_materials/index.html.twig', [
            'raw_materials' => $list,
            'searchForm' => $searchForm,
            'orders' => $lastOrders
        ]);
    }

    #[Route('/new', name: 'app_raw_materials_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RawMaterialsRepository $rawMaterialsRepository): Response
    {
        $rawMaterial = new RawMaterials();
        $form = $this->createForm(RawMaterialsType::class, $rawMaterial);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rawMaterialsRepository->save($rawMaterial, true);

            return $this->redirectToRoute('app_raw_materials_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('raw_materials/new.html.twig', [
            'raw_material' => $rawMaterial,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_raw_materials_show', methods: ['GET'])]
    public function show(RawMaterials $rawMaterial): Response
    {
        return $this->render('raw_materials/show.html.twig', [
            'raw_material' => $rawMaterial,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_raw_materials_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, RawMaterials $rawMaterial, RawMaterialsRepository $rawMaterialsRepository): Response
    {
        $form = $this->createForm(RawMaterialsType::class, $rawMaterial);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rawMaterialsRepository->save($rawMaterial, true);

            return $this->redirectToRoute('app_raw_materials_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('raw_materials/edit.html.twig', [
            'raw_material' => $rawMaterial,
            'form' => $form
        ]);
    }

    #[Route('/{id}', name: 'app_raw_materials_delete', methods: ['POST'])]
    public function delete(Request $request, RawMaterials $rawMaterial, RawMaterialsRepository $rawMaterialsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rawMaterial->getId(), $request->request->get('_token'))) {
            $rawMaterialsRepository->remove($rawMaterial, true);
        }

        return $this->redirectToRoute('app_raw_materials_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/ajax/orders/{searchOrder<\d*[a-zA-Z][a-zA-Z0-9]*>?}', name: 'app_last_10_orders', methods: ['GET'])]
    public function getLastOrders($searchOrder = null, OrdersRepository $ordersRepository)
    {
        if($searchOrder === null || $searchOrder === ''){
            $lastOrders = $ordersRepository->findBy([], ['id' => 'DESC'], 10, 0);
        } else {
            $lastOrders = $ordersRepository->findByName($searchOrder);
        }

        $lastOrdersNames = [];

        foreach ($lastOrders as $key => $order) {
            $orderName = $order->getNameOrder();
            $orderId = $order->getId();
            $tmpArray['id'] = $orderId;
            $tmpArray['name'] = $orderName;
            $lastOrdersNames[$orderName] = $tmpArray;
        }

        $lastOrdersNamesJson = json_encode($lastOrdersNames);
        // dd($lastOrdersNamesJson);

        return $this->render('orders/last10.html.twig', [
            'lastOrders' => $lastOrdersNamesJson
        ]);
    }
}

src/Controller/RawMaterialsController.php
<?php

namespace App\Controller;

use App\Entity\RawMaterials;
use App\Form\RawMaterialsType;
use App\Form\SearchFormType;
use App\Repository\OrdersRepository;
use App\Repository\RawMaterialsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/materiaux')]
class RawMaterialsController extends AbstractController
{
    #[Route('/', name: 'app_raw_materials_index', methods: ['GET', 'POST'])]
    public function index(RawMaterialsRepository $rawMaterialsRepository, Request $request, OrdersRepository $ordersRepository): Response
    {
        $rawMaterial = new RawMaterials();
        $searchForm = $this->createForm(SearchFormType::class, $rawMaterial, ['method' => 'POST']);
        $searchForm->handleRequest($request);

        $list = $rawMaterialsRepository->findAll();

        if ($searchForm->isSubmitted() && $searchForm->isValid()) {
            $search = $searchForm->getViewData()->getNameRawMaterial();
            $category = $searchForm->getViewData()->getCategory();
            $list = $rawMaterialsRepository->findByNameAndCategory($search, $category);
        }
        
        $lastOrders = $ordersRepository->findBy([], ['id' => 'DESC'], 10, 0);

        return $this->renderForm('raw_materials/index.html.twig', [
            'raw_materials' => $list,
            'searchForm' => $searchForm,
            'orders' => $lastOrders
        ]);
    }

    #[Route('/new', name: 'app_raw_materials_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RawMaterialsRepository $rawMaterialsRepository): Response
    {
        $rawMaterial = new RawMaterials();
        $form = $this->createForm(RawMaterialsType::class, $rawMaterial);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rawMaterialsRepository->save($rawMaterial, true);

            return $this->redirectToRoute('app_raw_materials_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('raw_materials/new.html.twig', [
            'raw_material' => $rawMaterial,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_raw_materials_show', methods: ['GET'])]
    public function show(RawMaterials $rawMaterial): Response
    {
        return $this->render('raw_materials/show.html.twig', [
            'raw_material' => $rawMaterial,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_raw_materials_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, RawMaterials $rawMaterial, RawMaterialsRepository $rawMaterialsRepository): Response
    {
        $form = $this->createForm(RawMaterialsType::class, $rawMaterial);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $rawMaterialsRepository->save($rawMaterial, true);

            return $this->redirectToRoute('app_raw_materials_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('raw_materials/edit.html.twig', [
            'raw_material' => $rawMaterial,
            'form' => $form
        ]);
    }

    #[Route('/{id}', name: 'app_raw_materials_delete', methods: ['POST'])]
    public function delete(Request $request, RawMaterials $rawMaterial, RawMaterialsRepository $rawMaterialsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rawMaterial->getId(), $request->request->get('_token'))) {
            $rawMaterialsRepository->remove($rawMaterial, true);
        }

        return $this->redirectToRoute('app_raw_materials_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/ajax/orders/{searchOrder<\d*[a-zA-Z][a-zA-Z0-9]*>?}', name: 'app_last_10_orders', methods: ['GET'])]
    public function getLastOrders($searchOrder = null, OrdersRepository $ordersRepository)
    {
        if($searchOrder === null || $searchOrder === ''){
            $lastOrders = $ordersRepository->findBy([], ['id' => 'DESC'], 10, 0);
        } else {
            $lastOrders = $ordersRepository->findByName($searchOrder);
        }

        $lastOrdersNames = [];

        foreach ($lastOrders as $key => $order) {
            $orderName = $order->getNameOrder();
            $orderId = $order->getId();
            $tmpArray['id'] = $orderId;
            $tmpArray['name'] = $orderName;
            $lastOrdersNames[$orderName] = $tmpArray;
        }

        $lastOrdersNamesJson = json_encode($lastOrdersNames);
        // dd($lastOrdersNamesJson);

        return $this->render('orders/last10.html.twig', [
            'lastOrders' => $lastOrdersNamesJson
        ]);
    }
}

templates/raw_materials/_delete_form.html.twig
<form method="post" action="{{ path('app_raw_materials_delete', {'id': raw_material.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce matériau ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ raw_material.id) }}">
    <button  class="btn btn-danger"><i class="fa fa-trash-can"></i></button>
</form>

templates/raw_materials/_form.html.twig
<div class="row mb-3">
    {{ form_start(form) }}
    <div class="col-12">
        {{ form_widget(form) }}
    </div>
    {{ form_end(form) }}
</div>

templates/raw_materials/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matériaux | Modification{% endblock %}

{% block body %}
    <div class="contain col-12 d-flex justify-content-between">
        <a href="{{ path('app_raw_materials_index') }}" class="btn btn-primary"><i class="fa-solid fa-reply"></i></a>
        {{ include('raw_materials/_delete_form.html.twig') }}
    </div>
    <h1 class="fs-2 text-center pt-5 container col-12 mx-auto">Modification du matériau</h1>
    <div class="mb-3 container col-11 col-sm-9 col-xl-6 col-xxl-4 mx-auto">
        {{ include('raw_materials/_form.html.twig', {'button_label': 'Enregistrer'}) }}
    </div>


{% endblock %}

templates/raw_materials/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matériaux | Liste{% endblock %}

{% block body %}
<div class="d-flex justify-content-center">
    <h1 class="col-12 col-sm-9 text-center fs-2">Liste des matériaux</h1>
</div>
    
<a href="{{ path('app_raw_materials_new') }}" class="btn btn-primary float-sm-end mt-2 col-6 col-sm-4 col-md-3 col-lg-2"><i class="fa fa-plus"></i> Ajouter</a>

<table class="table table-hover" id="table" data-toggle="table" data-search="true" data-locale="fr-FR" data-pagination="true">
    <thead>
        <tr>
            <th class="col-6 col-sm-3" data-sortable="true" data-field="name_raw_material">Matériaux</th>
            <th class="col-3 d-none d-sm-table-cell" data-sortable="true" data-field="category">Catégorie</th>
            <th class="col-1 d-none d-xl-table-cell" data-sortable="true" data-field="unity">Unité</th>
            <th class="col-1 d-none d-lg-table-cell" data-sortable="true" data-field="price">Prix HT(€)</th>
            <th class="col-6 col-sm-3 col-xl-2">Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for raw_material in raw_materials %}
    {% set index = loop.index %}
        <tr>
            <td>{{ raw_material.nameRawMaterial }}</td>
            <td>{{ raw_material.category }}</td>
            <td>{{ raw_material.unit }}</td>
            <td>{{ raw_material.price }}</td>
            <td>
                <a href="{{ path('app_raw_materials_show', {'id': raw_material.id}) }}" class="btn btn-primary"><i class="fa fa-eye"></i></a>
                <p class="btn btn-primary add-to-order-btn m-0" value="{{ loop.index }}" data-bs-toggle="modal" data-bs-target="#modal-material-{{ index }}"><i class="fa-solid fa-cart-plus"></i></p>
                <a href="{{ path('app_raw_materials_edit', {'id': raw_material.id}) }}" class="btn btn-success"><i class="fa-solid fa-pen-to-square"></i></a>
                <div class="modal fade" id="modal-material-{{ index }}">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h1 class="modal-title fs-6">A quelle commande et en quelle quantité voulez-vous ajouter : {{ raw_material.nameRawMaterial }} ?</h1>
                            <button type="button" class="btn-close ps-3 m-0" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body pb-0">
                            <div>
                                <label for="qtty">Quantité</label>
                                <input id="input-qtty-{{ index }}" name="qtty" type="number" required>
                            </div>
                            <div>
                                <form method="POST" action="" class="d-flex">
                                    <label for="order">Rechercher une commande</label>
                                    <input id="input-order-modal-{{ index }}" name="order" type="text" required>
                                    <input id="submit-order-modal-{{ index }}" type="submit" value="Rechercher">
                                </form>
                                
                            </div>
                            <div id="list-orders-{{ index }}" class="list-orders">
                                {% for order in orders %}
                                    <a class="worksites-links-{{ index }}" href="{{ path('app_raw_materials_ordered_new', {'idOrder': order.id, 'idRawMaterial': raw_material.id, 'qtty': 0}) }}">{{ order.nameOrder }}</a>
                                    <br>
                                {% endfor %}
                            </div>
                            <br>
                            <p class="mb-0">Ou créer une nouvelle commande :</p>
                            </div>
                            <div class="modal-footer justify-content-between">
                            <a href="{{ path('app_orders_new') }}">
                                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Créer une nouvelle commande</button>
                            </a>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                            </div>
                        </div>
                        </div>                        
                </div>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="4">Aucun matériaux enregistré</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.21.1/dist/locale/bootstrap-table-fr-FR.min.js"></script>
    {{ encore_entry_script_tags('app') }}
    <script src="{{ asset('js/rawMaterials.js') }}"></script>
{% endblock %}

templates/raw_materials/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matériaux | Ajouter{% endblock %}

{% block body %}
    <a href="{{ path('app_raw_materials_index') }}" class="btn btn-primary"><i class="fa-solid fa-reply"></i></a>
    <h1 class="fs-2 text-center pt-5 container col-12 mx-auto">Ajouter un matériau</h1>

    <div class="mb-3 container col-11 col-sm-9 col-xl-6 col-xxl-4 mx-auto">
        {{ include('raw_materials/_form.html.twig') }}
    </div>

{% endblock %}

templates/raw_materials/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Matériaux | Détails{% endblock %}

{% block body %}
<div class="d-flex justify-content-center">
    <h1 class="col-12 col-sm-9 text-center fs-2">Détails du matériau</h1>
</div>


    <table class="table">
        <tbody>
            <tr>
                <th>Matériau</th>
                <td>{{ raw_material.nameRawMaterial }}</td>
            </tr>
            <tr>
                <th>Date de création</th>
                <td>{{ raw_material.createdAt ? raw_material.createdAt|date('d M Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Nom de la catégorie</th>
                <td>{{ raw_material.category }}</td>
            </tr>
            <tr>
                <th>Unité</th>
                <td>{{ raw_material.unit }}</td>
            </tr>
            <tr>
                <th>Prix HT</th>
                <td>{{ raw_material.price }}</td>
            </tr>
        </tbody>
</table>

<div class="d-flex">
    <a href="{{ path('app_raw_materials_index') }}" class="btn btn-primary mb-3 me-2"><i class="fa-solid fa-reply"></i> Retour</a>

    <a href="{{ path('app_raw_materials_edit', {'id': raw_material.id}) }}" class="btn btn-primary mb-3 me-2">Modifier</a>

    {{ include('raw_materials/_delete_form.html.twig') }}
</div>
{% endblock %}