src/Entity/Repairs.php
<?php

namespace App\Entity;

use App\Repository\RepairsRepository;
use DateTimeImmutable;
use DateTimeZone;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RepairsRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Repairs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name_repair = null;

    #[ORM\Column(length: 255)]
    private ?string $city_repair = null;

    #[ORM\Column]
    private ?int $cp_repair = null;

    #[ORM\Column(length: 255)]
    private ?string $adress_repair = null;

    #[ORM\Column]
    private ?int $price_repair = null;

    #[ORM\Column]
    private ?int $reference_repair = null;

    #[ORM\Column(length: 255)]
    private ?string $schedule_repair = null;

    #[ORM\Column]
    private ?int $travel_distance_repair = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $note_admin_repair = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'repair_rental', targetEntity: Rentals::class)]
    private Collection $rental_repair;

    #[ORM\OneToMany(mappedBy: 'repair', targetEntity: RepairsImages::class)]
    private Collection $image_repair;


    public function __toString()
    {
        return $this->name_repair;
    }

    #[ORM\ManyToOne(inversedBy: 'repairs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Customers $client = null;

    #[ORM\ManyToOne(inversedBy: 'repairs')]
    #[ORM\JoinColumn(nullable: false, onDelete:"CASCADE")]
    private ?RepairsCategories $category = null;


    public function __construct()
    {
        $this->rental_repair = new ArrayCollection();
        $this->image_repair = new ArrayCollection();
        $date = new DateTimeImmutable();
        $timezone = new DateTimeZone('Europe/Paris');
        $this->created_at = $date->setTimezone($timezone);
    }

    #[ORM\PreUpdate]
    public function onPreUpdate()
    {
        $date = new DateTimeImmutable();
        $timezone = new DateTimeZone('Europe/Paris');
        $this->updated_at = $date->setTimezone($timezone);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameRepair(): ?string
    {
        return $this->name_repair;
    }

    public function setNameRepair(string $name_repair): self
    {
        $this->name_repair = $name_repair;

        return $this;
    }

    public function getCityRepair(): ?string
    {
        return $this->city_repair;
    }

    public function setCityRepair(string $city_repair): self
    {
        $this->city_repair = $city_repair;

        return $this;
    }

    public function getCpRepair(): ?int
    {
        return $this->cp_repair;
    }

    public function setCpRepair(int $cp_repair): self
    {
        $this->cp_repair = $cp_repair;

        return $this;
    }

    public function getAdressRepair(): ?string
    {
        return $this->adress_repair;
    }

    public function setAdressRepair(string $adress_repair): self
    {
        $this->adress_repair = $adress_repair;

        return $this;
    }

    public function getPriceRepair(): ?int
    {
        return $this->price_repair;
    }

    public function setPriceRepair(int $price_repair): self
    {
        $this->price_repair = $price_repair;

        return $this;
    }

    public function getReferenceRepair(): ?int
    {
        return $this->reference_repair;
    }

    public function setReferenceRepair(int $reference_repair): self
    {
        $this->reference_repair = $reference_repair;

        return $this;
    }

    public function getScheduleRepair(): ?string
    {
        return $this->schedule_repair;
    }

    public function setScheduleRepair(string $schedule_repair): self
    {
        $this->schedule_repair = $schedule_repair;

        return $this;
    }

    public function getTravelDistanceRepair(): ?int
    {
        return $this->travel_distance_repair;
    }

    public function setTravelDistanceRepair(int $travel_distance_repair): self
    {
        $this->travel_distance_repair = $travel_distance_repair;

        return $this;
    }

    public function getNoteAdminRepair(): ?string
    {
        return $this->note_admin_repair;
    }

    public function setNoteAdminRepair(?string $note_admin_repair): self
    {
        $this->note_admin_repair = $note_admin_repair;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Rentals>
     */
    public function getRentalRepair(): Collection
    {
        return $this->rental_repair;
    }

    public function addRentalRepair(Rentals $rentalRepair): self
    {
        if (!$this->rental_repair->contains($rentalRepair)) {
            $this->rental_repair->add($rentalRepair);
            $rentalRepair->setRepairRental($this);
        }

        return $this;
    }

    public function removeRentalRepair(Rentals $rentalRepair): self
    {
        if ($this->rental_repair->removeElement($rentalRepair)) {
            // set the owning side to null (unless already changed)
            if ($rentalRepair->getRepairRental() === $this) {
                $rentalRepair->setRepairRental(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RepairsImages>
     */
    public function getImageRepair(): Collection
    {
        return $this->image_repair;
    }

    public function addImageRepair(RepairsImages $imageRepair): self
    {
        if (!$this->image_repair->contains($imageRepair)) {
            $this->image_repair->add($imageRepair);
            $imageRepair->setRepair($this);
        }

        return $this;
    }

    public function removeImageRepair(RepairsImages $imageRepair): self
    {
        if ($this->image_repair->removeElement($imageRepair)) {
            // set the owning side to null (unless already changed)
            if ($imageRepair->getRepair() === $this) {
                $imageRepair->setRepair(null);
            }
        }

        return $this;
    }

    public function getClient(): ?Customers
    {
        return $this->client;
    }

    public function setClient(?Customers $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getCategory(): ?RepairsCategories
    {
        return $this->category;
    }

    public function setCategory(?RepairsCategories $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Entity/Worksites.php
<?php

namespace App\Entity;

use App\Repository\WorksitesRepository;
use DateTimeImmutable;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Nullable;

#[ORM\Entity(repositoryClass: WorksitesRepository::class)]
class Worksites
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name_worksite = null;

    #[ORM\Column(length: 255)]
    private ?string $city_worksite = null;

    #[ORM\Column]
    private ?int $cp_worksite = null;

    #[ORM\Column(length: 255)]
    private ?string $adress_worksite = null;

    #[ORM\Column]
    private ?\DateTime $start_at = null;

    #[ORM\Column]
    private ?int $duration_worksite = null;

    #[ORM\Column]
    private ?int $supplement_worksite = null;

    #[ORM\Column]
    private ?int $travel_distance_worksite = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $note_client_worksite = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $note_admin_worksite = null;

    #[ORM\Column(nullable: true)]
    private ?bool $is_urgent = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?WorksiteCategories $category_worksite = null;

    #[ORM\Column(length: 255)]
    private ?string $status_worksite = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'worksite', targetEntity: Tasks::class)]
    private Collection $task_worksite;

    #[ORM\OneToOne(mappedBy: 'worksite', cascade: ['persist', 'remove'])]
    private ?Quotation $quotation_worksite = null;

    #[ORM\OneToMany(mappedBy: 'worksite_rental', targetEntity: Rentals::class)]
    private Collection $rental_worksite;

    #[ORM\OneToMany(mappedBy: 'worksite', targetEntity: WorksiteImages::class)]
    private Collection $image_worksite;

    #[ORM\ManyToOne(inversedBy: 'worksite_customer')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Customers $client_worksite = null;

    #[ORM\OneToMany(mappedBy: 'worksite', targetEntity: Orders::class)]
    private Collection $orders;

    public function __construct()
    {
        $this->task_worksite = new ArrayCollection();
        $this->rental_worksite = new ArrayCollection();
        $this->image_worksite = new ArrayCollection();
        $this->created_at = new \DateTimeImmutable();
        $this->orders = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name_worksite;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameWorksite(): ?string
    {
        return $this->name_worksite;
    }

    public function setNameWorksite(string $name_worksite): self
    {
        $this->name_worksite = $name_worksite;

        return $this;
    }

    public function getCityWorksite(): ?string
    {
        return $this->city_worksite;
    }

    public function setCityWorksite(string $city_worksite): self
    {
        $this->city_worksite = $city_worksite;

        return $this;
    }

    public function getCpWorksite(): ?int
    {
        return $this->cp_worksite;
    }

    public function setCpWorksite(int $cp_worksite): self
    {
        $this->cp_worksite = $cp_worksite;

        return $this;
    }

    public function getAdressWorksite(): ?string
    {
        return $this->adress_worksite;
    }

    public function setAdressWorksite(string $adress_worksite): self
    {
        $this->adress_worksite = $adress_worksite;

        return $this;
    }

    public function getStartAt(): ?\DateTime
    {
        return $this->start_at;
    }

    public function setStartAt(\DateTime $start_at): self
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getDurationWorksite(): ?int
    {
        return $this->duration_worksite;
    }

    public function setDurationWorksite(?int $duration_worksite): self
    {
        $this->duration_worksite = $duration_worksite;

        return $this;
    }

    public function getSupplementWorksite(): ?int
    {
        return $this->supplement_worksite;
    }

    public function setSupplementWorksite(?int $supplement_worksite): self
    {
        $this->supplement_worksite = $supplement_worksite;

        return $this;
    }

    public function getTravelDistanceWorksite(): ?int
    {
        return $this->travel_distance_worksite;
    }

    public function setTravelDistanceWorksite(int $travel_distance_worksite): self
    {
        $this->travel_distance_worksite = $travel_distance_worksite;

        return $this;
    }

    public function getNoteClientWorksite(): ?string
    {
        return $this->note_client_worksite;
    }

    public function setNoteClientWorksite(?string $note_client_worksite): self
    {
        $this->note_client_worksite = $note_client_worksite;

        return $this;
    }

    public function getNoteAdminWorksite(): ?string
    {
        return $this->note_admin_worksite;
    }

    public function setNoteAdminWorksite(?string $note_admin_worksite): self
    {
        $this->note_admin_worksite = $note_admin_worksite;

        return $this;
    }

    public function getIsUrgent(): ?bool
    {
        return $this->is_urgent;
    }

    public function setIsUrgent($is_urgent): self
    {
        // if($is_urgent === null) {
        //     $this->is_urgent = false;
        // } else {
           $this->is_urgent = $is_urgent; 
        // }
        return $this;
    }

    public function getCategoryWorksite(): ?WorksiteCategories
    {
        return $this->category_worksite;
    }

    public function setCategoryWorksite(?WorksiteCategories $category_worksite): self
    {
        $this->category_worksite = $category_worksite;

        return $this;
    }

    public function getStatusWorksite(): ?string
    {
        return $this->status_worksite;
    }

    public function setStatusWorksite(string $status_worksite): self
    {
        $this->status_worksite = $status_worksite;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $timezone = new \DateTimeZone('Europe/Paris');
        $updated_at->setTimezone($timezone);

        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, WorksiteImages>
     */
    public function getImagesWorksite(): Collection
    {
        return $this->images_worksite;
    }

    public function addImagesWorksite(WorksiteImages $imagesWorksite): self
    {
        if (!$this->images_worksite->contains($imagesWorksite)) {
            $this->images_worksite->add($imagesWorksite);
            $imagesWorksite->setWorksite($this);
        }

        return $this;
    }

    public function removeImagesWorksite(WorksiteImages $imagesWorksite): self
    {
        if ($this->images_worksite->removeElement($imagesWorksite)) {
            if ($imagesWorksite->getWorksite() === $this)
            {
                $imagesWorksite->setWorksite(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Tasks>
     */
    public function getTaskWorksite(): Collection
    {
        return $this->task_worksite;
    }

    public function addTaskWorksite(Tasks $taskWorksite): self
    {
        if (!$this->task_worksite->contains($taskWorksite)) {
            $this->task_worksite->add($taskWorksite);
            $taskWorksite->setWorksite($this);
        }

        return $this;
    }

    public function removeTaskWorksite(Tasks $taskWorksite): self
    {
        if ($this->task_worksite->removeElement($taskWorksite)) {
            // set the owning side to null (unless already changed)
            if ($taskWorksite->getWorksite() === $this) {
                $taskWorksite->setWorksite(null);
            }
        }

        return $this;
    }

    public function getQuotationWorksite(): ?Quotation
    {
        return $this->quotation_worksite;
    }

    public function setQuotationWorksite(?Quotation $quotation_worksite): self
    {
        // set the owning side of the relation if necessary
        if ($quotation_worksite->getWorksite() !== $this) {
            $quotation_worksite->setWorksite($this);
        }

        $this->quotation_worksite = $quotation_worksite;

        return $this;
    }

    /**
     * @return Collection<int, Rentals>
     */
    public function getRentalWorksite(): Collection
    {
        return $this->rental_worksite;
    }

    public function addRentalWorksite(Rentals $rentalWorksite): self
    {
        if (!$this->rental_worksite->contains($rentalWorksite)) {
            $this->rental_worksite->add($rentalWorksite);
            $rentalWorksite->setWorksiteRental($this);
        }

        return $this;
    }

    public function removeRentalWorksite(Rentals $rentalWorksite): self
    {
        if ($this->rental_worksite->removeElement($rentalWorksite)) {
            // set the owning side to null (unless already changed)
            if ($rentalWorksite->getWorksiteRental() === $this) {
                $rentalWorksite->setWorksiteRental(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, WorksiteImages>
     */
    public function getImageWorksite(): Collection
    {
        return $this->image_worksite;
    }

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FBR Rénovation | Accueil{% endblock %}

{% block body %}
<div class="d-flex justify-content-center">
    <h1 class="col-12 col-sm-9 text-center fs-2">Bienvenue sur la page d'accueil de votre interface de gestion</h1>
</div>
<div class="d-flex justify-content-center pt-5">
    <div class="rounded-4 col-11 col-xl-10 col-xxl-9 bg-white d-flex justify-content-center p-3">
        <iframe class="col-12" src="https://calendar.google.com/calendar/embed?height=280&wkst=1&bgcolor=%23ffffff&ctz=Europe%2FParis&showTitle=0&showTz=1&src=amVzc3kuOTltaWxhcWlAZ21haWwuY29t&src=dTB0c2Q2ZHVhbW1qNzNnMnBhajE5ZzgwdmJrMWxpaGNAaW1wb3J0LmNhbGVuZGFyLmdvb2dsZS5jb20&color=%23039BE5&color=%23F09300" style="border-width:0" width="980" height="280" frameborder="0" scrolling="no"></iframe>
    </div>
</div>

<div class="d-flex justify-content-center pt-5">
    <div class="rounded-4 col-11 col-xl-10 col-xxl-9 bg-white d-flex flex-column justify-content-center p-3">
        <h3 class="fs-2">Chantiers</h3>
        <table class="table table-hover mt-4 col-12">
            <thead>
                <tr>
                    <th>Nom du chantier</th>
                    <th class="d-none d-lg-table-cell">Adresse</th>
                    <th class="d-none d-sm-table-cell">Client</th>
                    <th class="d-none d-sm-table-cell">Urgent</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for worksite in worksites %}
                <tr>
                    <td>{{ worksite.nameWorksite }}</td>
                    <td class="d-none d-lg-table-cell">{{ worksite.adressWorksite}}, {% if worksite.cpWorksite|length is same as 4 %}0{{ worksite.cpWorksite }}{% else %}{{worksite.cpWorksite}}{% endif %} {{ worksite.cityWorksite }}</td>
                    <td class="d-none d-sm-table-cell">{{ worksite.clientWorksite }}</td>
                    <td class="d-none d-sm-table-cell">{{ worksite.isUrgent ? 'Oui' : 'Non' }}</td>
                    <td>
                        <a href="{{ path('app_worksites_show', {'id': worksite.id}) }}" class="btn btn-primary btn-sm"><i class="fa fa-eye fa-fw"></i></a>
                        <a href="{{ path('app_worksites_edit', {'id': worksite.id}) }}" class="btn btn-success btn-sm"><i class="fa-solid fa-pen-to-square fa-fw"></i></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="16">Aucun chantier existant</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="d-flex justify-content-center pt-5">
    <div class="rounded-4 col-11 col-xl-10 col-xxl-9 bg-white d-flex flex-column justify-content-center p-3">
        <h3 class="fs-2">Dépannages</h3>
    
        <table class="table table-hover mt-4">
            <thead>
                <tr>
                    <th>Nom du dépannage</th>
                    <th class="d-none d-sm-table-cell">Adresse</th>
                    <th class="d-none d-md-table-cell">Client</th>
                    <th class="d-none d-lg-table-cell">Type de chantier</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for repair in repairs %}
                <tr>
                    <td>{{ repair.nameRepair }}</td>
                    <td class="d-none d-sm-table-cell">{{ repair.adressRepair }}, {% if repair.cpRepair|length is same as 4 %}0{{ repair.cpRepair }}{% else %}{{repair.cpRepair}}{% endif %} {{ repair.cityRepair }}</td>
                    <td class="d-none d-md-table-cell">{{ repair.client }}</td>
                    <td class="d-none d-lg-table-cell">{{ repair.category }}</td>
                    <td>
                        <a href="{{ path('app_repairs_show', {'id': repair.id}) }}" class="btn btn-primary btn-sm"><i class="fa fa-eye fa-fw"></i></a>
                        <a href="{{ path('app_repairs_edit', {'id': repair.id}) }}" class="btn btn-success btn-sm"><i class="fa-solid fa-pen-to-square fa-fw"></i></a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="13">Aucun dépannage enregistré</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}