src/Entity/Repairs.php
<?php

namespace App\Entity;

use App\Repository\RepairsRepository;
use DateTimeImmutable;
use DateTimeZone;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RepairsRepository::class)]
#[ORM\HasLifecycleCallbacks]
class Repairs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name_repair = null;

    #[ORM\Column(length: 255)]
    private ?string $city_repair = null;

    #[ORM\Column]
    private ?int $cp_repair = null;

    #[ORM\Column(length: 255)]
    private ?string $adress_repair = null;

    #[ORM\Column]
    private ?int $price_repair = null;

    #[ORM\Column]
    private ?int $reference_repair = null;

    #[ORM\Column(length: 255)]
    private ?string $schedule_repair = null;

    #[ORM\Column]
    private ?int $travel_distance_repair = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $note_admin_repair = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\OneToMany(mappedBy: 'repair_rental', targetEntity: Rentals::class)]
    private Collection $rental_repair;

    #[ORM\OneToMany(mappedBy: 'repair', targetEntity: RepairsImages::class)]
    private Collection $image_repair;


    public function __toString()
    {
        return $this->name_repair;
    }

    #[ORM\ManyToOne(inversedBy: 'repairs')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Customers $client = null;

    #[ORM\ManyToOne(inversedBy: 'repairs')]
    #[ORM\JoinColumn(nullable: false, onDelete:"CASCADE")]
    private ?RepairsCategories $category = null;


    public function __construct()
    {
        $this->rental_repair = new ArrayCollection();
        $this->image_repair = new ArrayCollection();
        $date = new DateTimeImmutable();
        $timezone = new DateTimeZone('Europe/Paris');
        $this->created_at = $date->setTimezone($timezone);
    }

    #[ORM\PreUpdate]
    public function onPreUpdate()
    {
        $date = new DateTimeImmutable();
        $timezone = new DateTimeZone('Europe/Paris');
        $this->updated_at = $date->setTimezone($timezone);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameRepair(): ?string
    {
        return $this->name_repair;
    }

    public function setNameRepair(string $name_repair): self
    {
        $this->name_repair = $name_repair;

        return $this;
    }

    public function getCityRepair(): ?string
    {
        return $this->city_repair;
    }

    public function setCityRepair(string $city_repair): self
    {
        $this->city_repair = $city_repair;

        return $this;
    }

    public function getCpRepair(): ?int
    {
        return $this->cp_repair;
    }

    public function setCpRepair(int $cp_repair): self
    {
        $this->cp_repair = $cp_repair;

        return $this;
    }

    public function getAdressRepair(): ?string
    {
        return $this->adress_repair;
    }

    public function setAdressRepair(string $adress_repair): self
    {
        $this->adress_repair = $adress_repair;

        return $this;
    }

    public function getPriceRepair(): ?int
    {
        return $this->price_repair;
    }

    public function setPriceRepair(int $price_repair): self
    {
        $this->price_repair = $price_repair;

        return $this;
    }

    public function getReferenceRepair(): ?int
    {
        return $this->reference_repair;
    }

    public function setReferenceRepair(int $reference_repair): self
    {
        $this->reference_repair = $reference_repair;

        return $this;
    }

    public function getScheduleRepair(): ?string
    {
        return $this->schedule_repair;
    }

    public function setScheduleRepair(string $schedule_repair): self
    {
        $this->schedule_repair = $schedule_repair;

        return $this;
    }

    public function getTravelDistanceRepair(): ?int
    {
        return $this->travel_distance_repair;
    }

    public function setTravelDistanceRepair(int $travel_distance_repair): self
    {
        $this->travel_distance_repair = $travel_distance_repair;

        return $this;
    }

    public function getNoteAdminRepair(): ?string
    {
        return $this->note_admin_repair;
    }

    public function setNoteAdminRepair(?string $note_admin_repair): self
    {
        $this->note_admin_repair = $note_admin_repair;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection<int, Rentals>
     */
    public function getRentalRepair(): Collection
    {
        return $this->rental_repair;
    }

    public function addRentalRepair(Rentals $rentalRepair): self
    {
        if (!$this->rental_repair->contains($rentalRepair)) {
            $this->rental_repair->add($rentalRepair);
            $rentalRepair->setRepairRental($this);
        }

        return $this;
    }

    public function removeRentalRepair(Rentals $rentalRepair): self
    {
        if ($this->rental_repair->removeElement($rentalRepair)) {
            // set the owning side to null (unless already changed)
            if ($rentalRepair->getRepairRental() === $this) {
                $rentalRepair->setRepairRental(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RepairsImages>
     */
    public function getImageRepair(): Collection
    {
        return $this->image_repair;
    }

    public function addImageRepair(RepairsImages $imageRepair): self
    {
        if (!$this->image_repair->contains($imageRepair)) {
            $this->image_repair->add($imageRepair);
            $imageRepair->setRepair($this);
        }

        return $this;
    }

    public function removeImageRepair(RepairsImages $imageRepair): self
    {
        if ($this->image_repair->removeElement($imageRepair)) {
            // set the owning side to null (unless already changed)
            if ($imageRepair->getRepair() === $this) {
                $imageRepair->setRepair(null);
            }
        }

        return $this;
    }

    public function getClient(): ?Customers
    {
        return $this->client;
    }

    public function setClient(?Customers $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getCategory(): ?RepairsCategories
    {
        return $this->category;
    }

    public function setCategory(?RepairsCategories $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/RepairsType.php
<?php

namespace App\Form;

use App\Entity\Repairs;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Customers;
use App\Entity\RepairsCategories;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class RepairsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name_repair', TextType::class, ['label' => 'Nom', 'label_attr' => ['class' => 'mb-1, mt-2']])
            ->add('city_repair', TextType::class, ['label' => 'Ville', 'label_attr' => ['class' => 'mb-1, mt-2']])
            ->add('cp_repair', IntegerType::class, ['label' => 'Code postal', 'label_attr' => ['class' => 'mb-1, mt-2']])
            ->add('adress_repair', TextType::class, ['label' => 'Adresse', 'label_attr' => ['class' => 'mb-1, mt-2']])
            ->add('price_repair', IntegerType::class, ['label' => 'Prix(€)', 'label_attr' => ['class' => 'mb-1, mt-2']])
            ->add('reference_repair', IntegerType::class, ['label' => 'Référence du dépannage', 'label_attr' => ['class' => 'mb-1, mt-2']])
            ->add('schedule_repair', ChoiceType::class, [
                'choices' => [
                    'Jour' => 'Jour',
                    'Nuit' => 'Nuit',
                    'Weekend' => 'Weekend'
                ],
                'label' => 'horaire',
                'label_attr' => ['class' => 'mb-1, mt-2']
            ])
            ->add('travel_distance_repair', IntegerType::class, ['label' => 'Distance(km)', 'label_attr' => ['class' => 'mb-1, mt-2']])
            ->add('note_admin_repair', TextType::class, ['label' => 'Note', 'required' => false, 'label_attr' => ['class' => 'mb-1, mt-2']])
            ->add('client', EntityType::class, ['class' => Customers::class, 'label_attr' => ['class' => 'mb-1, mt-2']])
            ->add('category', EntityType::class, ['class' => RepairsCategories::class, 'label_attr' => ['class' => 'mb-1, mt-2']])
            ->add('submit', SubmitType::class, ['label' => 'Enregistrer', 'attr' => ['class' => 'btn btn-success mt-3']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Repairs::class,
        ]);
    }
}

src/Controller/Admin/RepairsController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Repairs;
use App\Form\RepairsType;
use App\Repository\RepairsImagesRepository;
use App\Repository\RepairsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/depannages')]
class RepairsController extends AbstractController
{
    #[Route('/', name: 'app_repairs_index', methods: ['GET'])]
    public function index(RepairsRepository $repairsRepository): Response
    {
        return $this->render('repairs/index.html.twig', [
            'repairs' => $repairsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_repairs_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RepairsRepository $repairsRepository): Response
    {
        $repair = new Repairs();
        $form = $this->createForm(RepairsType::class, $repair);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $repairsRepository->save($repair, true);

            return $this->redirectToRoute('app_repairs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('repairs/new.html.twig', [
            'repair' => $repair,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_repairs_show', methods: ['GET'])]
    public function show(Repairs $repair, RepairsImagesRepository $repairsImagesRepository): Response
    {
        $repairImages = $repairsImagesRepository->findByRepair($repair->getId());
        return $this->render('repairs/show.html.twig', [
            'repair' => $repair,
            'images' => $repairImages,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_repairs_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Repairs $repair, RepairsRepository $repairsRepository): Response
    {
        $form = $this->createForm(RepairsType::class, $repair);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $repairsRepository->save($repair, true);

            return $this->redirectToRoute('app_repairs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('repairs/edit.html.twig', [
            'repair' => $repair,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_repairs_delete', methods: ['POST'])]
    public function delete(Request $request, Repairs $repair, RepairsRepository $repairsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$repair->getId(), $request->request->get('_token'))) {
            $repairsRepository->remove($repair, true);
        }

        return $this->redirectToRoute('app_repairs_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/RepairsController.php
<?php

namespace App\Controller;

use App\Entity\Repairs;
use App\Form\RepairsType;
use App\Repository\RepairsImagesRepository;
use App\Repository\RepairsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/repairs')]
class RepairsController extends AbstractController
{
    #[Route('/', name: 'app_repairs_index', methods: ['GET'])]
    public function index(RepairsRepository $repairsRepository): Response
    {
        return $this->render('repairs/index.html.twig', [
            'repairs' => $repairsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_repairs_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RepairsRepository $repairsRepository): Response
    {
        $repair = new Repairs();
        $form = $this->createForm(RepairsType::class, $repair);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $repairsRepository->save($repair, true);

            return $this->redirectToRoute('app_repairs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('repairs/new.html.twig', [
            'repair' => $repair,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_repairs_show', methods: ['GET'])]
    public function show(Repairs $repair, RepairsImagesRepository $repairsImagesRepository): Response
    {
        $repairImages = $repairsImagesRepository->findByRepair($repair->getId());
        return $this->render('repairs/show.html.twig', [
            'repair' => $repair,
            'images' => $repairImages,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_repairs_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Repairs $repair, RepairsRepository $repairsRepository): Response
    {
        $form = $this->createForm(RepairsType::class, $repair);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $repairsRepository->save($repair, true);

            return $this->redirectToRoute('app_repairs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('repairs/edit.html.twig', [
            'repair' => $repair,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_repairs_delete', methods: ['POST'])]
    public function delete(Request $request, Repairs $repair, RepairsRepository $repairsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$repair->getId(), $request->request->get('_token'))) {
            $repairsRepository->remove($repair, true);
        }

        return $this->redirectToRoute('app_repairs_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/repairs/_delete_form.html.twig
<form method="post" action="{{ path('app_repairs_delete', {'id': repair.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce dépannage ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ repair.id) }}">
    <button class="btn btn-danger"><i class="fa fa-trash-can"></i></button>
</form>

templates/repairs/_form.html.twig
<div class="row mb-3">
    {{ form_start(form, { 'attr': {'class': 'p-0'} }) }}
    <div class="col-12">
        {{ form_widget(form) }}
    </div>
    {{ form_end(form) }}
</div>

templates/repairs/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dépannage | Modifications{% endblock %}

{% block body %}
    <div class="contain col-12 d-flex justify-content-between">
        <a href="{{ path('app_repairs_index') }}" class="btn btn-primary"><i class="fa-solid fa-reply"></i></a>
        {{ include('repairs/_delete_form.html.twig') }}
    </div>
    <h1 class="fs-2 text-center pt-5 container col-12 mx-auto">Modifier les informations du dépannage</h1>
    <div class="mb-3 container col-11 col-sm-9 col-xl-6 col-xxl-4 mx-auto">
        {{ include('repairs/_form.html.twig', {'button_label': 'Enregistrer'}) }}
        
    </div>
    

    
{% endblock %}

templates/repairs/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Les dépannages{% endblock %}

{% block body %}
<div class="d-flex justify-content-center">
    <h1 class="col-12 col-sm-9 text-center fs-2">Liste des dépannages</h1>
</div>

<a href="{{ path('app_repairs_new') }}" class="btn btn-primary float-sm-end mt-2 col-6 col-sm-4 col-md-3 col-lg-2"><i class="fa fa-plus"></i> Ajouter</a>

<table class="table table-hover" id="table" data-toggle="table" data-search="true" data-locale="fr-FR" data-pagination="true">
    <thead>
        <tr>
            <th data-sortable="true" data-field="repairName">Dépannage</th>
            <th data-sortable="true" data-field="reference" class="d-none d-md-table-cell">Référence</th>
            <th data-sortable="true" data-field="address" class="d-none d-sm-table-cell">Adresse</th>
            <th data-sortable="true" data-field="price" class="d-none d-md-table-cell">Prix(€)</th>
            <th data-sortable="true" data-field="customer" class="d-none d-lg-table-cell">Client</th>
            <th data-sortable="true" data-field="category" class="d-none d-xl-table-cell">Catégorie</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for repair in repairs %}
        <tr>
            <td>{{ repair.nameRepair }}</td>
            <td>{{ repair.referenceRepair }}</td>
            <td>{{ repair.adressRepair }}, {% if repair.cpRepair|length is same as 4 %}0{{ repair.cpRepair }}{% else %}{{repair.cpRepair}}{% endif %} {{ repair.cityRepair }}</td>
            <td>{{ repair.priceRepair }}</td>
            <td>{{ repair.client }}</td>
            <td>{{ repair.category }}</td>
            <td>
                <a href="{{ path('app_repairs_show', {'id': repair.id}) }}" class="btn btn-primary btn-sm mb-2"><i class="fa-fw fa fa-eye"></i></a>
                <a href="{{ path('app_repairs_edit', {'id': repair.id}) }}" class="btn btn-success btn-sm mb-2"><i class="fa-fw fa-solid fa-pen-to-square"></i></a>
            </td>
        </tr>
    {% else %}
        <tr>
            <td colspan="13">Aucun dépannage trouvé</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/repairs/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dépannage | Nouveau{% endblock %}

{% block body %}
    <a href="{{ path('app_repairs_index') }}" class="btn btn-primary mb-3"><i class="fa-solid fa-reply"></i></a>
    <h1 class="fs-2 text-center pt-5 container col-12 mx-auto">Ajouter un dépannage</h1>
    <div class="mb-3 container col-11 col-sm-9 col-xl-6 col-xxl-4 mx-auto">
        {{ include('repairs/_form.html.twig') }}
    </div>
    
{% endblock %}

templates/repairs/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dépannage{% endblock %}

{% block body %}
<div class="d-flex justify-content-center">
    <h1 class="col-12 col-sm-9 text-center fs-2">Détails du dépannage</h1>
</div>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom dépannage</th>
                <td>{{ repair.nameRepair }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ repair.cityRepair }}</td>
            </tr>
            <tr>
                <th>Code postal</th>
                <td>{% if repair.cpRepair|length is same as 4 %}0{{ repair.cpRepair }}{% else %}{{repair.cpRepair}}{% endif %}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ repair.adressRepair }}</td>
            </tr>
            <tr>
                <th>Prix(€)</th>
                <td>{{ repair.priceRepair }}</td>
            </tr>
            <tr>
                <th>Référence</th>
                <td>{{ repair.referenceRepair }}</td>
            </tr>
            <tr>
                <th>Horaire</th>
                <td>{{ repair.scheduleRepair }}</td>
            </tr>
            <tr>
                <th>Distance(km)</th>
                <td>{{ repair.travelDistanceRepair }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{% if (repair.noteAdminRepair is same as null) or (repair.noteAdminRepair is same as '') %}Pas de note{% else %}{{ repair.noteAdminRepair }}{% endif %}</td>
            </tr>
            <tr>
                <th>Client</th>
                <td>{{ repair.client }}</td>
            </tr>
            <tr>
                <th>Catégorie</th>
                <td>{{ repair.category }}</td>
            </tr>
            <tr>
                <th>Date de création</th>
                <td>{{ repair.createdAt ? repair.createdAt|date('d M Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date de modification</th>
                <td>{{ repair.updatedAt ? repair.updatedAt|date('d M Y H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Images</th>
                <td>
                    {% for image in images %}
                    {% if image.mimeType != 'application/pdf' %}
                    <img src="{{ vich_uploader_asset(image) }}" alt="" width="200">
                    {% endif %}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Documents</th>
                <td>
                    {% for image in images %}
                    {% if image.mimeType == 'application/pdf' %}
                    <iframe src="{{ vich_uploader_asset(image) }}" frameborder="0" width="800" height="500"></iframe>
                    {% endif %}
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    <div class="d-flex">
        <a href="{{ path('app_repairs_index') }}" class="btn btn-primary mb-3 me-2"><i class="fa-solid fa-reply"></i> Retour</a>

        <a href="{{ path('app_repairs_edit', {'id': repair.id}) }}"class="btn btn-primary mb-3 me-2">Modifier</a>
    
        <div title="Add to Calendar" class="addeventatc btn btn-light mb-3 me-2" data-styling="">
            <span class="timezone">Europe/Paris</span>
            <span class="title">{{ repair.nameRepair }}</span>
            <span class="description">Horaire : {{ repair.scheduleRepair }} , <br> Distance : {{ repair.travelDistanceRepair }} km, <br> Client : {{ repair.client }}</span>
            <span class="location">{{ repair.adressRepair }}, {% if repair.cpRepair|length is same as 4 %}0{{ repair.cpRepair }}{% else %}{{repair.cprepair}}{% endif %} {{ repair.cityRepair }}</span>
        </div>
        {{ include('repairs/_delete_form.html.twig') }}
    </div>
{% endblock %}