src/Entity/Designation.php
<?php

namespace App\Entity;

use App\Repository\DesignationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DesignationRepository::class)]
class Designation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $unity = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column]
    private ?float $price_unitary_ht = null;

    #[ORM\Column]
    private ?int $tva = null;

    #[ORM\ManyToOne(inversedBy: 'designations')]
    private ?Quotation $quotation = null;

    #[ORM\Column]
    private ?float $Price_ht = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $designation = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUnity(): ?string
    {
        return $this->unity;
    }

    public function setUnity(string $unity): self
    {
        $this->unity = $unity;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPriceUnitaryHt(): ?float
    {
        return $this->price_unitary_ht;
    }

    public function setPriceUnitaryHt(float $price_unitary_ht): self
    {
        $this->price_unitary_ht = $price_unitary_ht;

        return $this;
    }

    public function getTva(): ?int
    {
        return $this->tva;
    }

    public function setTva(int $tva): self
    {
        $this->tva = $tva;

        return $this;
    }

    public function getQuotation(): ?Quotation
    {
        return $this->quotation;
    }

    public function setQuotation(?Quotation $quotation): self
    {
        $this->quotation = $quotation;

        return $this;
    }

    public function getPriceHt(): ?float
    {
        return $this->Price_ht;
    }

    public function setPriceHt($quantity, $price_unitary_ht): self
    {
        $this->Price_ht = $price_unitary_ht * $quantity;

        return $this;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }
}

src/Form/DesignationType.php
<?php

namespace App\Form;

use App\Entity\Designation;
use App\Entity\Quotation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DesignationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('designation', TextareaType::class, ['label' => 'Désignation'])
            ->add('unity', TextType::class, ['label' => 'Unité'])
            ->add('quantity', IntegerType::class, ['label' => 'Quantité'])
            ->add('price_unitary_ht', MoneyType::class, ['label' => 'Prix unitaire HT(€)'])
            ->add('tva', IntegerType::class, ['label' => 'TVA(%)'])
            ->add('quotation', EntityType::class, ['label' => 'Devis', 'class' => Quotation::class])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Designation::class,
        ]);
    }
}

src/Controller/Admin/DesignationController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Designation;
use App\Form\DesignationType;
use App\Repository\DesignationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/designation')]
class DesignationController extends AbstractController
{
    #[Route('/', name: 'app_designation_index', methods: ['GET'])]
    public function index(DesignationRepository $designationRepository): Response
    {
        return $this->render('designation/index.html.twig', [
            'designations' => $designationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_designation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DesignationRepository $designationRepository): Response
    {
        $designation = new Designation();
        $form = $this->createForm(DesignationType::class, $designation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $designation->setPriceHt($request->get('designation')['quantity'], $request->get('designation')['price_unitary_ht']);
            $designationRepository->save($designation, true);

            return $this->redirectToRoute('app_quotation_show', ['id' => $request->get('designation')['quotation']], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('designation/new.html.twig', [
            'designation' => $designation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_designation_show', methods: ['GET'])]
    public function show(Designation $designation): Response
    {
        return $this->render('designation/show.html.twig', [
            'designation' => $designation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_designation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Designation $designation, DesignationRepository $designationRepository): Response
    {
        $form = $this->createForm(DesignationType::class, $designation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $designationRepository->save($designation, true);

            return $this->redirectToRoute('app_quotation_show', ['id' => $request->get('designation')['quotation']], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('designation/edit.html.twig', [
            'designation' => $designation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_designation_delete', methods: ['POST'])]
    public function delete(Request $request, Designation $designation, DesignationRepository $designationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$designation->getId(), $request->request->get('_token'))) {
            $designationRepository->remove($designation, true);
        }

        return $this->redirectToRoute('app_quotation_show', ['id' => $designation->getQuotation()->getId()], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/DesignationController.php
<?php

namespace App\Controller;

use App\Entity\Designation;
use App\Form\DesignationType;
use App\Repository\DesignationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/designation')]
class DesignationController extends AbstractController
{
    #[Route('/', name: 'app_designation_index', methods: ['GET'])]
    public function index(DesignationRepository $designationRepository): Response
    {
        return $this->render('designation/index.html.twig', [
            'designations' => $designationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_designation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DesignationRepository $designationRepository): Response
    {
        $designation = new Designation();
        $form = $this->createForm(DesignationType::class, $designation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $designation->setPriceHt($request->get('designation')['quantity'], $request->get('designation')['price_unitary_ht']);
            $designationRepository->save($designation, true);

            return $this->redirectToRoute('app_quotation_show', ['id' => $request->get('designation')['quotation']], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('designation/new.html.twig', [
            'designation' => $designation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_designation_show', methods: ['GET'])]
    public function show(Designation $designation): Response
    {
        return $this->render('designation/show.html.twig', [
            'designation' => $designation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_designation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Designation $designation, DesignationRepository $designationRepository): Response
    {
        $form = $this->createForm(DesignationType::class, $designation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $designationRepository->save($designation, true);

            return $this->redirectToRoute('app_quotation_show', ['id' => $request->get('designation')['quotation']], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('designation/edit.html.twig', [
            'designation' => $designation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_designation_delete', methods: ['POST'])]
    public function delete(Request $request, Designation $designation, DesignationRepository $designationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$designation->getId(), $request->request->get('_token'))) {
            $designationRepository->remove($designation, true);
        }

        return $this->redirectToRoute('app_quotation_show', ['id' => $designation->getQuotation()->getId()], Response::HTTP_SEE_OTHER);
    }
}

templates/designation/_delete_form.html.twig
<form method="post" action="{{ path('app_designation_delete', {'id': designation.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce désignation?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ designation.id) }}">
    <button class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash-can"></i></button>
</form>

templates/designation/_form.html.twig
<div class="row mb-3">
    {{ form_start(form) }}
        <div class="col-12">
            {{ form_widget(form) }}
        </div>
        <button class="btn btn-success mt-3 mb-2">{{ button_label|default('Enregistrer') }}</button>
    {{ form_end(form) }}
</div>

templates/designation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Devis | Modification de désignations{% endblock %}

{% block body %}

    <div class="contain col-12 d-flex justify-content-between">
        <a href="{{ path('app_quotation_show', {'id': designation.quotation.id}) }}" class="btn btn-primary btn-sm"><i class="fa-solid fa-reply"></i></a>
        {{ include('designation/_delete_form.html.twig') }}
    </div>
    <h1 class="fs-2 text-center pt-5 container col-12 mx-auto">Modifier la désignation</h1>
    
    <div class="mb-3 container col-11 col-sm-9 col-xl-6 col-xxl-4 mx-auto">
        {{ include('designation/_form.html.twig', {'button_label': 'Enregistrer'}) }}
    </div>
        
{% endblock %}

templates/designation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Designation index{% endblock %}

{% block body %}
    <h1>Designation index</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Unité</th>
                <th>Quantité</th>
                <th>Prix unitaire HT</th>
                <th>Prix HT</th>
                <th>TVa</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for designation in designations %}
            <tr>
                <td>{{ designation.name }}</td>
                <td>{{ designation.unity }}</td>
                <td>{{ designation.quantity }}</td>
                <td>{{ designation.priceUnitaryHt }}</td>
                <td>{{ designation.priceHt }}</td>
                <td>{{ designation.tva }}</td>
                <td>
                    <a href="{{ path('app_designation_show', {'id': designation.id}) }}" class="btn btn-primary"><i class="fa fa-eye"></i></a>
                    <a href="{{ path('app_designation_edit', {'id': designation.id}) }}" class="btn btn-success"><i class="fa-solid fa-pen-to-square"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_designation_new') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Créer </a>
{% endblock %}

templates/designation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Devis | Nouvelle désignation{% endblock %}

{% block body %}
<a href="{{ path('app_quotation_index') }}" class="btn btn-primary mb-3"><i class="fa-solid fa-reply"></i></a>
<h1 class="fs-2 text-center pt-5 container col-12 mx-auto">Créer une nouvelle désignation</h1>
<div class="mb-3 container col-11 col-sm-9 col-xl-6 col-xxl-4 mx-auto">
    {{ include('designation/_form.html.twig') }}
</div>
{% endblock %}

templates/designation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Designation{% endblock %}

{% block body %}
    <h1>Designation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ designation.name }}</td>
            </tr>
            <tr>
                <th>Unité</th>
                <td>{{ designation.unity }}</td>
            </tr>
            <tr>
                <th>Quantité</th>
                <td>{{ designation.quantity }}</td>
            </tr>
            <tr>
                <th>Prix unitaire HT</th>
                <td>{{ designation.priceUnitaryHt }}</td>
            </tr>
            <tr>
                <th>TVA</th>
                <td>{{ designation.tva }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_designation_index') }}" class="btn btn-primary mb-2"><i class="fa-solid fa-reply"></i> Retour </a>

    <a href="{{ path('app_designation_edit', {'id': designation.id}) }}" class="btn btn-primary mb-2">Modifier</a>

    {{ include('designation/_delete_form.html.twig') }}
{% endblock %}